import { Product } from "@/app/interfaces/product.interface";

export const products:Product[] = [
  { id: 1, name: 'MacBook Pro 14"', price: 1999, image: 'https://placehold.co/400' },
  { id: 2, name: 'iPhone 15 Pro', price: 999, image: 'https://placehold.co/400' },
  { id: 3, name: 'Sony WH-1000XM5 Headphones', price: 399, image: 'https://placehold.co/400' },
  { id: 4, name: 'Apple Watch Ultra 2', price: 799, image: 'https://placehold.co/400' },
  { id: 5, name: 'Samsung Galaxy S24 Ultra', price: 1199, image: 'https://images.samsung.com/us/smartphones/galaxy-s24-ultra/images/galaxy-s24-ultra-highlights-kv.jpg' },
  { id: 6, name: 'Dell XPS 17', price: 2399, image: 'https://placehold.co/400' },
  { id: 7, name: 'PlayStation 5', price: 499, image: 'https://placehold.co/400' },
  { id: 8, name: 'Xbox Series X', price: 499, image: 'https://placehold.co/400' },
  { id: 9, name: 'Nintendo Switch OLED', price: 349, image: 'https://m.media-amazon.com/images/I/61ZNIHIEUqL._AC_SL1500_.jpg' },
  { id: 10, name: 'LG C3 OLED TV 55"', price: 1399, image: 'https://placehold.co/400' },
  { id: 11, name: 'Bose SoundLink Revolve+ Bluetooth Speaker', price: 329, image: 'https://placehold.co/400' },
  { id: 12, name: 'Logitech MX Master 3S Wireless Mouse', price: 99, image: 'https://placehold.co/400' },
  { id: 13, name: 'Razer Huntsman Elite Gaming Keyboard', price: 199, image: 'https://placehold.co/400' },
  { id: 14, name: 'GoPro HERO12 Black', price: 399, image: 'https://placehold.co/400' },
  { id: 16, name: 'DJI Mini 4 Pro Drone', price: 759, image: 'https://placehold.co/400' },
  { id: 17, name: 'Apple iPad Pro 12.9"', price: 1099, image: 'https://placehold.co/400' },
  { id: 18, name: 'Amazon Kindle Paperwhite', price: 149, image: 'https://placehold.co/400' },
  { id: 19, name: 'Samsung Galaxy Tab S9', price: 799, image: 'https://placehold.co/400' },
  { id: 20, name: 'Apple AirPods Pro (2nd Gen)', price: 249, image: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_SL1500_.jpg' },
  { id: 21, name: 'Anker PowerCore 26800 Power Bank', price: 79, image: 'https://placehold.co/400' },
  { id: 22, name: 'Fitbit Charge 6 Fitness Tracker', price: 159, image: 'https://placehold.co/400' },
  { id: 23, name: 'NVIDIA GeForce RTX 4090', price: 1599, image: 'https://placehold.co/400' },
  { id: 24, name: 'Corsair Vengeance RGB 32GB RAM', price: 99, image: 'https://placehold.co/400' },
  { id: 25, name: 'WD Black 2TB NVMe SSD', price: 199, image: 'https://placehold.co/400' },
  { id: 26, name: 'Eero Pro 6E Mesh WiFi System', price: 499, image: 'https://placehold.co/400' },
  { id: 27, name: 'Elgato Stream Deck MK.2', price: 149, image: 'https://placehold.co/400' },
  { id: 28, name: 'Roku Ultra 4K Streaming Device', price: 99, image: 'https://placehold.co/400' },
  { id: 29, name: 'Samsung 49" Odyssey Neo G9 Monitor', price: 1799, image: 'https://placehold.co/400' }
];
